// Builds icons/icons.js from icons/icons.txt using the Tabler outline set
// (the icon set SALT uses — same names, 24px grid, 2px stroke).
// Needs: npm i @tabler/icons   (run anywhere with npm access, e.g. Cowork)
// Usage: node scripts/build-icons.mjs [path/to/node_modules/@tabler/icons]
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const pkg = process.argv[2] || path.join(root, "node_modules/@tabler/icons");
const nodes = JSON.parse(fs.readFileSync(path.join(pkg, "tabler-nodes-outline.json"), "utf8"));
const version = JSON.parse(fs.readFileSync(path.join(pkg, "package.json"), "utf8")).version;

const names = fs.readFileSync(path.join(root, "icons/icons.txt"), "utf8")
  .split("\n").map(s => s.trim()).filter(s => s && !s.startsWith("#"));

const out = {}, missing = [];
for (const n of names) {
  if (!nodes[n]) { missing.push(n); continue; }
  out[n] = nodes[n].map(([tag, attrs]) =>
    `<${tag} ${Object.entries(attrs).filter(([k]) => k !== "key").map(([k, v]) => `${k}="${v}"`).join(" ")}/>`
  ).join("");
}
if (missing.length) { console.error("Unknown icon names:", missing.join(", ")); process.exit(1); }

const js = `/* icons.js — GENERATED by scripts/build-icons.mjs. Do not edit.
   Tabler Icons v${version} (MIT), outline. ${Object.keys(out).length} icons.
   Usage:  <span class="tm-icon" data-icon="phone"></span>   then nothing else —
   icons render on load. For JS-created markup call TMIcons.render(root).
   Or get markup:  TMIcons.svg("phone")                                        */
(function () {
  var P = ${JSON.stringify(out)};
  function svg(name) {
    if (!P[name]) { console.warn("[TMIcons] unknown icon:", name); return ""; }
    return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' + P[name] + "</svg>";
  }
  function render(root) {
    (root || document).querySelectorAll("[data-icon]").forEach(function (el) {
      el.innerHTML = svg(el.getAttribute("data-icon"));
    });
  }
  window.TMIcons = { svg: svg, render: render, names: Object.keys(P) };
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", function () { render(); });
  else render();
})();
`;
fs.writeFileSync(path.join(root, "icons/icons.js"), js);
console.log(`icons.js written: ${Object.keys(out).length} icons (Tabler ${version})`);
