#!/usr/bin/env python3
"""Build truemeds.css from the SALT token export.

Inputs  (never hand-edit — re-export from Figma instead):
  tokens/Core.tokens.json      raw palette + scales
  tokens/Default.tokens.json   semantic names that point at Core
  tokens/extras.json           values SALT documents but does not export
                               (shadows, text styles) — copied from the
                               SALT Figma pages, see the file for sources
  src/components.css           hand-written components, tokens only

Output:
  truemeds.css                 the one file every project links

Run:  python3 scripts/build.py   (no dependencies)
"""
import json
import re
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def slug(*parts):
    s = "-".join(parts).lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-")


def walk(node, path):
    """Yield (path list, token dict) for every token in a DTCG tree."""
    if isinstance(node, dict) and "$value" in node:
        yield path, node
        return
    if isinstance(node, dict):
        for k, v in node.items():
            if not k.startswith("$"):
                yield from walk(v, path + [k])


def core_var(path):
    # Colour/Blue/Blue 500 -> --tm-core-blue-500 ; Space/8 -> --tm-core-space-8
    if path[0] == "Colour":
        return "--tm-core-" + slug(path[-1])
    return "--tm-core-" + slug(*path)


def sem_var(path):
    # Colour/Content/Primary -> --tm-content-primary
    # Colour/Surface/Brand/Default -> --tm-surface-brand-default
    # Space/lg -> --tm-space-lg ; Font/Size/Body/md -> --tm-font-size-body-md
    if path[0] == "Colour":
        return "--tm-" + slug(*path[1:])
    return "--tm-" + slug(*path)


def px(name, value):
    if isinstance(value, (int, float)) and not name.startswith(("--tm-core-opacity", "--tm-overlay")):
        return f"{value}px"
    return str(value)


def color_value(tok):
    v = tok["$value"]
    if isinstance(v, str):
        return v
    hexv = v["hex"].upper()
    a = v.get("alpha", 1)
    if a < 1:
        r, g, b = (round(c * 255) for c in v["components"])
        return f"rgba({r}, {g}, {b}, {a:g})"
    return hexv


def build_core():
    data = json.loads((ROOT / "tokens/Core.tokens.json").read_text())
    lines, index = [], {}
    for path, tok in walk(data, []):
        if path[0] in ("Font",) and path[1] == "Weight":
            continue  # weights are emitted from Default as numbers
        name = core_var(path)
        if tok["$type"] == "color":
            val = color_value(tok)
        elif tok["$type"] == "string":
            val = f'"{tok["$value"]}"'
        else:
            val = px(name, tok["$value"])
        lines.append(f"  {name}: {val};")
        index["/".join(path)] = name
    return lines, index


WEIGHTS = {"Regular": 400, "Medium": 500, "Semibold": 600, "Bold": 700, "Extrabold": 800}


def build_semantic(core_index):
    data = json.loads((ROOT / "tokens/Default.tokens.json").read_text())
    lines = []
    for path, tok in walk(data, []):
        name = sem_var(path)
        v = tok["$value"]
        alias = tok.get("$extensions", {}).get("com.figma.aliasData", {}).get("targetVariableName")
        if isinstance(v, str) and v.startswith("{"):
            ref = v.strip("{}").split(".")
            val = f"var({sem_var(ref)})"
        elif path[:2] == ["Font", "Weight"]:
            val = str(WEIGHTS[v])
        elif path[:2] == ["Font", "Family"]:
            val = f'"{v}", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif'
        elif alias and alias in core_index:
            val = f"var({core_index[alias]})"
        elif tok["$type"] == "color":
            val = color_value(tok)
        else:
            val = px(name, v)
        lines.append(f"  {name}: {val};")
    return lines


def build_extras():
    ex = json.loads((ROOT / "tokens/extras.json").read_text())
    lines = []
    for k, v in ex["shadow"].items():
        if k.startswith("_"):
            continue
        lines.append(f"  --tm-shadow-{k}: {v};")
    classes = []
    for k, v in ex["text"].items():
        if k.startswith("_"):
            continue
        size, lh, weight = v
        classes.append(
            f".tm-text-{k} {{ font-size: {size}px; line-height: {lh}px; font-weight: {weight}; }}"
        )
    return lines, classes


def main():
    core, idx = build_core()
    sem = build_semantic(idx)
    ex_vars, text_classes = build_extras()
    components = (ROOT / "src/components.css").read_text()
    out = [
        "/* ==========================================================",
        "   truemeds.css — GENERATED by scripts/build.py. Do not edit.",
        "   Source: SALT (TRUEMEDS Design Library, App) token export.",
        f"   Built: {date.today().isoformat()}",
        "   Change values in Figma → re-export JSON → rerun build.",
        "   ========================================================== */",
        "",
        "/* Plus Jakarta Sans (SIL OFL) — bundled in fonts/, works offline and on file:// */",
        '@font-face { font-family: "Plus Jakarta Sans"; font-style: normal; font-weight: 200 800; font-display: swap; src: url("fonts/plus-jakarta-sans-latin-wght-normal.woff2") format("woff2"); }',
        '@font-face { font-family: "Plus Jakarta Sans"; font-style: italic; font-weight: 200 800; font-display: swap; src: url("fonts/plus-jakarta-sans-latin-wght-italic.woff2") format("woff2"); }',
        "",
        "/* ---- 1. Core palette & scales (do NOT use directly in projects) ---- */",
        ":root {",
        *core,
        "}",
        "",
        "/* ---- 2. Semantic tokens (USE THESE) ---- */",
        ":root {",
        *sem,
        "",
        "  /* Shadows — from SALT › Shadow page (not in the variable export) */",
        *ex_vars,
        "}",
        "",
        "/* ---- 3. Text styles — from SALT › Font page ---- */",
        *text_classes,
        "",
        "/* ---- 4. Components — from src/components.css ---- */",
        components,
    ]
    (ROOT / "truemeds.css").write_text("\n".join(out))
    print(f"truemeds.css written: {len(core)} core, {len(sem)} semantic, "
          f"{len(ex_vars)} shadows, {len(text_classes)} text styles")
    build_preview(sem, ex_vars)


def build_preview(sem, ex_vars):
    """Fill src/preview.template.html with the live token lists."""
    names = [l.split(":")[0].strip() for l in sem]
    groups = {}
    for n in names:
        key = n.split("-")[3]  # --tm-<group>-…: content / surface / border / feedback / space / radius / font
        groups.setdefault(key, []).append(n)

    def swatches(keys):
        cells = []
        for k in keys:
            for n in groups.get(k, []):
                cells.append(
                    f'<div class="sw"><span style="background:var({n})"></span>'
                    f"<code>{n}</code></div>"
                )
        return "\n".join(cells)

    space = "\n".join(
        f'<div class="sp"><span style="width:var({n})"></span><code>{n}</code></div>'
        for n in groups.get("space", []) if not n.endswith("none")
    )
    radius = "\n".join(
        f'<div class="rd"><span style="border-radius:var({n})"></span><code>{n}</code></div>'
        for n in groups.get("radius", [])
    )
    shadows = "\n".join(
        f'<div class="sh"><span style="box-shadow:var({l.split(":")[0].strip()})"></span>'
        f'<code>{l.split(":")[0].strip()}</code></div>'
        for l in ex_vars
    )
    ex = json.loads((ROOT / "tokens/extras.json").read_text())["text"]
    texts = "\n".join(
        f'<div class="ty"><span class="tm-text-{k}">Paracetamol 650 mg</span>'
        f"<code>.tm-text-{k} · {v[0]}/{v[1]} · {v[2]}</code></div>"
        for k, v in ex.items() if not k.startswith("_")
    )
    tpl = (ROOT / "src/preview.template.html").read_text()
    html = (tpl.replace("{{COLOURS_CONTENT}}", swatches(["content"]))
               .replace("{{COLOURS_SURFACE}}", swatches(["surface"]))
               .replace("{{COLOURS_BORDER}}", swatches(["border", "feedback"]))
               .replace("{{SPACE}}", space).replace("{{RADIUS}}", radius)
               .replace("{{SHADOWS}}", shadows).replace("{{TEXT}}", texts)
               .replace("{{BUILT}}", date.today().isoformat()))
    (ROOT / "preview.html").write_text(html)
    print("preview.html written")


if __name__ == "__main__":
    main()
