// Builds icons/icons.js from icons/icons.txt using the Tabler outline set
// (the icon set SALT uses — same names, 24px grid, 2px stroke).
// Needs: npm i @tabler/icons   (run anywhere with npm access, e.g. Cowork)
// Usage: node scripts/build-icons.mjs [path/to/node_modules/@tabler/icons]
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const pkg = process.argv[2] || path.join(root, "node_modules/@tabler/icons");
const nodes = JSON.parse(fs.readFileSync(path.join(pkg, "tabler-nodes-outline.json"), "utf8"));
const version = JSON.parse(fs.readFileSync(path.join(pkg, "package.json"), "utf8")).version;

const names = fs.readFileSync(path.join(root, "icons/icons.txt"), "utf8")
  .split("\n").map(s => s.trim()).filter(s => s && !s.startsWith("#"));

const out = {}, missing = [];
for (const n of names) {
  if (!nodes[n]) { missing.push(n); continue; }
  out[n] = nodes[n].map(([tag, attrs]) =>
    `<${tag} ${Object.entries(attrs).filter(([k]) => k !== "key").map(([k, v]) => `${k}="${v}"`).join(" ")}/>`
  ).join("");
}
if (missing.length) { console.error("Unknown icon names:", missing.join(", ")); process.exit(1); }

// [PROPOSED] Medicine-form glyphs Tabler doesn't have, drawn on Tabler's grid (24px, 2px stroke,
// round caps, one colour). Agreed with Apurva 2026-10-09; renders in projects/truemeds-doctor-portal-prototype/docs/renders/2026-10-09/.
// Tablet is drawn at an angle (line drawing, no shading): a flat circle with a bar reads as "no entry" / "minus".
out["tablet"]        = '<path d="M3 10.5a9 4.5 0 1 0 18 0a9 4.5 0 1 0 -18 0"/><path d="M3 10.5v3a9 4.5 0 0 0 18 0v-3"/><path d="M8 7.3l8 6.4"/>';
out["syrup"]         = '<path d="M6 6v-3h4v3"/><path d="M4 9a3 3 0 0 1 3 -3h2a3 3 0 0 1 3 3v10a2 2 0 0 1 -2 2h-4a2 2 0 0 1 -2 -2z"/><path d="M14 12h7l-.8 8.1a1 1 0 0 1 -1 .9h-3.4a1 1 0 0 1 -1 -.9z"/><path d="M15.8 15h1.7"/><path d="M16 17.8h1.5"/>';      // bottle + measuring cup
out["eye-drops"]     = '<g transform="translate(1 2.2) rotate(-35 11 7)"><path d="M7 1.5h8a1 1 0 0 1 1 1v5.5a2 2 0 0 1 -2 2h-6a2 2 0 0 1 -2 -2v-5.5a1 1 0 0 1 1 -1z"/><path d="M9 10v2h4v-2"/><path d="M10.2 12l.8 3l.8 -3"/></g><path d="M16.8 17.8l-1.7 2.5a2.1 2.1 0 1 0 3.4 0z"/>';      // tilted dropper bottle + drop
out["ointment-tube"] = '<g transform="rotate(45 12 12)"><path d="M7 2.5h10v2.5h-10z"/><path d="M7.5 5h9l-1.8 11.5h-5.4z"/><path d="M10.5 16.5v1.5h3v-1.5"/><path d="M10 18h4v3.5h-4z"/></g>';
out["inhaler"]       = '<path d="M8 8v-4.5a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v4.5"/><path d="M8 5h4"/><path d="M5 8h9v6h5a1 1 0 0 1 1 1v4a1 1 0 0 1 -1 1h-12a2 2 0 0 1 -2 -2z"/><path d="M17 16.5v1.5"/>';    // L-shaped puffer

const js = `/* icons.js — GENERATED by scripts/build-icons.mjs. Do not edit.
   Tabler Icons v${version} (MIT), outline. ${Object.keys(out).length} icons.
   Usage:  <span class="tm-icon" data-icon="phone"></span>   then nothing else —
   icons render on load. For JS-created markup call TMIcons.render(root).
   Or get markup:  TMIcons.svg("phone")                                        */
(function () {
  var P = ${JSON.stringify(out)};
  function svg(name) {
    if (!P[name]) { console.warn("[TMIcons] unknown icon:", name); return ""; }
    return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' + P[name] + "</svg>";
  }
  function render(root) {
    (root || document).querySelectorAll("[data-icon]").forEach(function (el) {
      el.innerHTML = svg(el.getAttribute("data-icon"));
    });
  }
  window.TMIcons = { svg: svg, render: render, names: Object.keys(P) };
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", function () { render(); });
  else render();
})();
`;
fs.writeFileSync(path.join(root, "icons/icons.js"), js);
console.log(`icons.js written: ${Object.keys(out).length} icons (Tabler ${version})`);
